version: '3.8'  # Se não estiver especificado, é bom adicionar a versão do compose.

services:
  djangoapp:
    container_name: djangoapp
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./djangoapp:/djangoapp
      - ./data/web/static:/data/web/static/
      - ./data/web/media:/data/web/media/
    env_file:
      - ./dotenv_files/.env
    depends_on:
      - psql

  psql:
    container_name: psql
    image: postgres:13-alpine
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data/
    env_file:
      - ./dotenv_files/.env

  test:
    build:
      context: .
    command: ["coverage", "run", "-m", "pytest"] # Use o caminho completo do coverage
    environment:
      - DJANGO_SETTINGS_MODULE=minitwitter.settings
      - TESTING=1
    env_file:
      - ./dotenv_files/.env 
    volumes:
      - ./djangoapp:/djangoapp
      - ./scripts:/scripts
    depends_on:
      - psql
    profiles: 
      - test